# Generated by Django 4.2.1 on 2023-05-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='busroute',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
