# Generated by Django 4.2.1 on 2023-05-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_remove_ticket_price_busroute_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='duration',
        ),
    ]
