# Generated by Django 4.2.1 on 2023-05-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_remove_busroute_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
