# Generated by Django 4.2.1 on 2023-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='purchase_datetime',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(default=0),
        ),
    ]
