# Generated by Django 4.2.1 on 2023-05-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_remove_ticket_purchase_datetime_ticket_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(default=1),
        ),
    ]
