# Generated by Django 4.2.1 on 2023-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_alter_ticket_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
    ]
