# Generated by Django 4.2.1 on 2023-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_alter_bus_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cin',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
